-- Table: public.luxe_user

-- DROP TABLE IF EXISTS public.luxe_user;

CREATE TABLE IF NOT EXISTS public.luxe_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    firstname character varying(255) NOT NULL,
    lastname character varying(255) NOT NULL,
    password character varying(255),
    updated_at timestamp(6) without time zone,
    username character varying(255) NOT NULL,
    CONSTRAINT luxe_user_pkey PRIMARY KEY (id),
    CONSTRAINT uk337d9s24vgcc0x9rb02orfooo UNIQUE (username),
    CONSTRAINT ukauhyfk0wenfni3wjsn1v5v9h6 UNIQUE (email)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.luxe_user
    OWNER to neondb_owner;

-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(255),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to neondb_owner;


-- Table: public.webauthncredential

-- DROP TABLE IF EXISTS public.webauthncredential;

CREATE TABLE IF NOT EXISTS public.webauthncredential
(
    credentialid character varying(255) NOT NULL,
    aaguid uuid,
    counter bigint NOT NULL,
    publickey bytea,
    publickeyalgorithm bigint NOT NULL,
    user_id bigint,
    CONSTRAINT webauthncredential_pkey PRIMARY KEY (credentialid),
    CONSTRAINT ukt4138ofj9y5yisqv1nva191lc UNIQUE (user_id),
    CONSTRAINT fk3rdbllm4orjfnu1aaqqtyuh2q FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.webauthncredential
    OWNER to neondb_owner;

