-- Create table to store WebAuthn credentials
CREATE TABLE IF NOT EXISTS public.webauthn_credential (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    credential_id TEXT NOT NULL UNIQUE,
    authenticator JSONB NOT NULL,
    counter bigint NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Speed up username lookups
CREATE INDEX IF NOT EXISTS ix_webauthn_authenticator_username
    ON webauthn_credential (username, credential_id);

